# 通过函数：快速的逐元素数组函数

In [2]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#很多通用函数是简单的逐元素转换，你如事情sqrt，exp.称为一元通用函数：
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [7]:
# np.add(),np.maximum()...接收两个数组并返回一个数组的结果--二元通用函数：
x = np.random.randn(8)
x

array([-0.59942313, -0.2180478 , -0.50117735, -0.29580606,  2.72560567,
        0.50711557,  1.46659603,  1.06251753])

In [8]:
y = np.random.randn(8)
y

array([-1.34682481, -0.30347206, -0.2846675 , -0.5973595 , -0.5439439 ,
       -0.60850391, -1.05844119, -0.23140847])

In [9]:
np.maximum(x,y)

array([-0.59942313, -0.2180478 , -0.2846675 , -0.29580606,  2.72560567,
        0.50711557,  1.46659603,  1.06251753])

In [10]:
arr = np.random.randn(7) * 5
arr

array([ 1.88612466, -0.69982606, -3.15319908,  0.35632166,  2.0485544 ,
       -3.79709028,  5.05572147])

In [11]:
# 返回福讴歌数组的通用函数：
# np.modf()返回一个浮点值数组的小数部分和整数部分
remainder,whole_part = np.modf(arr)
remainder

array([ 0.88612466, -0.69982606, -0.15319908,  0.35632166,  0.0485544 ,
       -0.79709028,  0.05572147])

In [12]:
whole_part

array([ 1., -0., -3.,  0.,  2., -3.,  5.])

In [13]:
arr

array([ 1.88612466, -0.69982606, -3.15319908,  0.35632166,  2.0485544 ,
       -3.79709028,  5.05572147])

In [14]:
np.sqrt(arr)

/Users/totore/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([1.37336254,        nan,        nan, 0.59692685, 1.43127719,
              nan, 2.24849315])

In [15]:
np.sqrt(arr,arr)   #out=arr ,指明输出结果存储的位置

/Users/totore/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([1.37336254,        nan,        nan, 0.59692685, 1.43127719,
              nan, 2.24849315])

In [16]:
arr

array([1.37336254,        nan,        nan, 0.59692685, 1.43127719,
              nan, 2.24849315])

# 常见的一元通用函数：

函数名	描述
abs、fabs	逐个元素地计算整数、浮点数或复数地绝对值
sqrt	计算每个元素的平方根(与arr ** 0.5相等)
square	计算每个元素地平方(与arr ** 2相等)
exp	计算每个元素的自然指数值e^x次方
log、log10、log2、log1p	分别对应(自然指数(e为底)、对数10为底、对数2为底、log(1+x))
sign	计算每个元素的符号值：1(正数)、0(0)、-1(负数)
ceil	计算每个元素的最高整数值(即大于等于给定数值的最小整数)
floor	计算每个元素的最小整数值(即小于等于给定整数的最大整数)
rint	将元素保留到整数位，并保持dtype
modf	分别将数组的小数部分与整数部分按数组形式返回
isnan	返回数组元素是否是一个NaN(非数值)，形式为布尔值数组
isfinite、isinf	分别返回数组中的元素是否有限(非inf、非NaN)、是否无限的，形式为布尔值数组
cos、cish、sin、	常规三角函数及双曲三角函数
sinh、tan、tanh	
arccos、arccosh、arcsin、	反三角函数
arcsinh、arctan、arctanh	
logical_not	对数组元素按位取反(与~arr效果一样)

In [20]:
arr = np.random.randn(8)
arr

array([ 1.70322567, -0.76947883, -0.4084229 , -1.148202  , -0.18405926,
        1.88221729,  0.61140403,  2.33673608])

In [24]:
np.logical_not(arr<0)

array([ True, False, False, False, False,  True,  True,  True])

In [29]:
arr[~(arr<0]

array([1.70322567, 1.88221729, 0.61140403, 2.33673608])

# 常用的二元通用函数 

add	将数组的对应元素相加
subtract	在第二个数组中，将第一个数组中包含的元素去除
multiply	将数组的对应元素相乘
divide,floor_divide	除或整除(放弃余数)
power	将第二个数组的元素作为第一个数组对应元素的幂次方
maximum	逐个元素计算最大值，fmax忽略NaN
minimum	逐个元素计算最小值，fmin忽略NaN
mod	按元素的求模计算(即求除法的余数)
copysign	将第一个数组的符号值改为第二个数组的符号值
greater,greater_equal,less，	进行逐个元素的比较，返回布尔值数组（与数学操作符>,>=,<,<=,==,!=x效果一致）
less_equal,equal,not_equal	（接上）
logical_and,logical_or	进行逐个元素的逻辑操作(与逻辑操作符&、丨、^效果一致)
logical_xor	

In [30]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([2,3,2,3])

In [31]:
np.power(arr1,arr2)

array([ 1,  8,  9, 64])

In [34]:
np.maximum(arr1,arr2)

array([2, 3, 3, 4])

In [35]:
np.floor_divide(arr1,arr2)

array([0, 0, 1, 1])

In [39]:
np.mod(arr1,arr2)

array([1, 2, 1, 1])