## 处理缺失值: 

In [315]:
import pandas as pd
import numpy as np

In [316]:
string_data = pd.Series(['aardvark','artichoke',np.nan,'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [317]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [318]:
string_data[0]  = None

In [319]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [320]:
#NA处理方法

In [321]:
# dropna  
# fillna 
# isnull  
# notnull

### 过滤缺失值：dropna

In [322]:
from numpy import nan as NA

In [323]:
data = pd.Series([1,NA,3.5,NA,7])

In [324]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [325]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [326]:
data = pd.DataFrame([[1.,6.5,3.],[1.,NA,NA],[NA,NA,NA],[NA,6.5,3.]])

In [327]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [328]:
cleaned = data.dropna()

In [329]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [330]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [331]:
data[4] = NA

In [332]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [333]:
data.dropna(axis=1,how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [334]:
df = pd.DataFrame(np.random.randn(7,3))
df

0         1         2
0  1.007189 -1.296221  0.274992
1  0.228913  1.352917  0.886429
2 -2.001637 -0.371843  1.669025
3 -0.438570 -0.539741  0.476985
4  3.248944 -1.021228 -0.577087
5  0.124121  0.302614  0.523772
6  0.000940  1.343810 -0.713544

In [335]:
df.iloc[:4,1] = NA

In [336]:
df.iloc[:2,2] = NA
df

0         1         2
0  1.007189       NaN       NaN
1  0.228913       NaN       NaN
2 -2.001637       NaN  1.669025
3 -0.438570       NaN  0.476985
4  3.248944 -1.021228 -0.577087
5  0.124121  0.302614  0.523772
6  0.000940  1.343810 -0.713544

In [337]:
df.dropna()

0         1         2
4  3.248944 -1.021228 -0.577087
5  0.124121  0.302614  0.523772
6  0.000940  1.343810 -0.713544

In [338]:
#如果想保留一定数量的观察值行使用thresh参数来表示：

In [339]:
df.dropna(thresh=2)

0         1         2
2 -2.001637       NaN  1.669025
3 -0.438570       NaN  0.476985
4  3.248944 -1.021228 -0.577087
5  0.124121  0.302614  0.523772
6  0.000940  1.343810 -0.713544

### 补全缺失值:fillna

In [340]:
df

0         1         2
0  1.007189       NaN       NaN
1  0.228913       NaN       NaN
2 -2.001637       NaN  1.669025
3 -0.438570       NaN  0.476985
4  3.248944 -1.021228 -0.577087
5  0.124121  0.302614  0.523772
6  0.000940  1.343810 -0.713544

In [341]:
df.fillna(0)

0         1         2
0  1.007189  0.000000  0.000000
1  0.228913  0.000000  0.000000
2 -2.001637  0.000000  1.669025
3 -0.438570  0.000000  0.476985
4  3.248944 -1.021228 -0.577087
5  0.124121  0.302614  0.523772
6  0.000940  1.343810 -0.713544

In [342]:
#调用fillna使用字典，可为不同列设定不同的填充值：

In [343]:
df.fillna({1:0.5,2:0})

0         1         2
0  1.007189  0.500000  0.000000
1  0.228913  0.500000  0.000000
2 -2.001637  0.500000  1.669025
3 -0.438570  0.500000  0.476985
4  3.248944 -1.021228 -0.577087
5  0.124121  0.302614  0.523772
6  0.000940  1.343810 -0.713544

In [344]:
_ = df.fillna(0,inplace=True)

In [345]:
df

0         1         2
0  1.007189  0.000000  0.000000
1  0.228913  0.000000  0.000000
2 -2.001637  0.000000  1.669025
3 -0.438570  0.000000  0.476985
4  3.248944 -1.021228 -0.577087
5  0.124121  0.302614  0.523772
6  0.000940  1.343810 -0.713544

In [346]:
df = pd.DataFrame(np.random.randn(6,3))
df

0         1         2
0 -0.831154 -2.370232 -1.860761
1 -0.860757  0.560145 -1.265934
2  0.119827 -1.063512  0.332883
3 -2.359419 -0.199543 -1.541996
4 -0.970736 -1.307030  0.286350
5  0.377984 -0.753887  0.331286

In [347]:
df.iloc[2:,1] = NA
df.iloc[4:,2] = NA

In [348]:
df

0         1         2
0 -0.831154 -2.370232 -1.860761
1 -0.860757  0.560145 -1.265934
2  0.119827       NaN  0.332883
3 -2.359419       NaN -1.541996
4 -0.970736       NaN       NaN
5  0.377984       NaN       NaN

In [349]:
df.fillna(method='ffill')

0         1         2
0 -0.831154 -2.370232 -1.860761
1 -0.860757  0.560145 -1.265934
2  0.119827  0.560145  0.332883
3 -2.359419  0.560145 -1.541996
4 -0.970736  0.560145 -1.541996
5  0.377984  0.560145 -1.541996

In [350]:
df.fillna(method='ffill',limit=2)

0         1         2
0 -0.831154 -2.370232 -1.860761
1 -0.860757  0.560145 -1.265934
2  0.119827  0.560145  0.332883
3 -2.359419  0.560145 -1.541996
4 -0.970736       NaN -1.541996
5  0.377984       NaN -1.541996

In [351]:
data = pd.Series([1,NA,3.5,NA,7])

In [352]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## 数据转换

In [353]:
#删除重复值

In [354]:
data = pd.DataFrame({'k1':['one','two']*3 + ['two'],
                     'k2':[1,1,2,3,3,4,4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [355]:
#data.duplicated()返回一个布尔值，反映每一行的值是否存在重复（与之前一行相比）

In [356]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [357]:
data.drop_duplicates()  #删除与之前一行相比的重复行

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [358]:
data['v1'] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [359]:
#基于k1列去重
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [360]:
#duplicated和drop_duplicates默认都是保留第一个观测值，传入参数keep='last'将会返回最后一个：
data.drop_duplicates(['k1','k2'],keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [361]:
data.drop_duplicates(['k1','k2'])

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5

### 使用函数或映射进行数据转换

In [362]:
#map只用于series
#apply用于series或者dataframe
#applymap用于dataframe的每一个值

In [363]:
data = pd.DataFrame({'food':['bacon','pulled pork','bacon','Pastrami','corned beef',
                             'Bacon','pastrami','honey ham','nova lox'],
                    'ounces':[4,3,12,6,7.5,8,3,5,6]})

In [364]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [365]:
meat_to_animal = {
    'bacon':'pig',
    'pulled pork':'pig',
    'pastrami':'cow',
    'corned beef':'cow',
    'honey ham':'pig',
    'nova lox':'salmon'
}

In [366]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [367]:
data['animal'] = data['food'].apply(lambda x: meat_to_animal[x.lower()])

In [368]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [369]:
data['animal2'] = data.apply(lambda x: meat_to_animal[x['food'].lower()],axis=1)

In [370]:
data

food  ounces  animal animal2
0        bacon     4.0     pig     pig
1  pulled pork     3.0     pig     pig
2        bacon    12.0     pig     pig
3     Pastrami     6.0     cow     cow
4  corned beef     7.5     cow     cow
5        Bacon     8.0     pig     pig
6     pastrami     3.0     cow     cow
7    honey ham     5.0     pig     pig
8     nova lox     6.0  salmon  salmon

In [371]:
data['animal3'] = data['food'].map(lambda x: meat_to_animal[x.lower()])

In [372]:
data

food  ounces  animal animal2 animal3
0        bacon     4.0     pig     pig     pig
1  pulled pork     3.0     pig     pig     pig
2        bacon    12.0     pig     pig     pig
3     Pastrami     6.0     cow     cow     cow
4  corned beef     7.5     cow     cow     cow
5        Bacon     8.0     pig     pig     pig
6     pastrami     3.0     cow     cow     cow
7    honey ham     5.0     pig     pig     pig
8     nova lox     6.0  salmon  salmon  salmon

### 替代值 data.replace()

In [373]:
data = pd.Series([1.,-999.,2.,-999.,-1000.,3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [374]:
#-999可能是缺失值的标志，如果使用NA来替代这些值，可以使用replace方法生成新的series

In [375]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [376]:
#一次性替代多个值，可传入一个列表和替代值：

In [377]:
data.replace([-999,-1000],np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [378]:
#将不同值替换为不同值，可传入替代值的列表：
data.replace([-999,-1000],[np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [379]:
#参数也可以通过字典传递：
data.replace({-999:np.nan,-1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [380]:
#data.replace()和data.str.replace()方法是不同的，data.str.replace是对字符串进行按元素替代。

### 重命名轴索引 data.index.map()  data.rename(index=,columns=)

In [535]:
data =pd.DataFrame(np.arange(12).reshape(3,4),index=['Ohio','Colorado','New York'],columns=['one','two','three','four'])

In [536]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [537]:
#与series类型，轴索引也有一个map方法：

In [538]:
transform = lambda x: x[:4].upper()

In [539]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [540]:
#赋值给index，修改df：
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [542]:
data.indexe'wa

<method 'title' of 'str' objects>

In [387]:
data.rename(index=str.title,columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [388]:
data.rename(index={'OHIO':'INDIANA'},columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [389]:
#rename后修改原有的数据集，传入inplace=True
data.rename(index={'OHIO':'INDIANA'},columns={'three':'peekaboo'},inplace=True)

In [390]:
data

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

### 离散化和分箱

In [391]:
#连续值经常需要离散化，或者分离成’箱子‘进行分析。假设某研究中一组人群的数据，想将其进行分组，放入离散的年龄框：

In [392]:
import random
y = list(range(20,70))
ages = random.sample(y,12)
ages

[69, 68, 56, 59, 62, 65, 64, 33, 63, 20, 40, 54]

In [393]:
#将年龄分为18~25，26~35，36~60以及60以上等若干组。使用pandas.cut

In [394]:
bins = [18,25,35,60,100]
cats = pd.cut(ages,bins)

In [395]:
cats

[(60, 100], (60, 100], (35, 60], (35, 60], (60, 100], ..., (25, 35], (60, 100], (18, 25], (35, 60], (35, 60]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [396]:
cats.codes

array([3, 3, 2, 2, 3, 3, 3, 1, 3, 0, 2, 2], dtype=int8)

In [397]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [398]:
pd.value_counts(cats)
#这里是对pd.cut结果中箱数量的计数

(60, 100]    6
(35, 60]     4
(25, 35]     1
(18, 25]     1
dtype: int64

In [399]:
#通过传递right=False来改变封闭区间
cats = pd.cut(ages,[18,26,36,61,100],right=False)

In [400]:
cats

[[61, 100), [61, 100), [36, 61), [36, 61), [61, 100), ..., [26, 36), [61, 100), [18, 26), [36, 61), [36, 61)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [401]:
group_names = ['youth','youngadult','middleaged','senior']
pd.cut(ages,bins,labels=group_names)

[senior, senior, middleaged, middleaged, senior, ..., youngadult, senior, youth, middleaged, middleaged]
Length: 12
Categories (4, object): [youth < youngadult < middleaged < senior]

In [402]:
#传给cut整数个的箱来代替显式的箱边,pandas将根据数据中最大值最小值计算出等长的箱。

In [403]:
data = np.random.rand(20)
data

array([0.97322998, 0.63405438, 0.88842172, 0.49541476, 0.35161653,
       0.71423037, 0.50392912, 0.22563761, 0.24497444, 0.7928007 ,
       0.49517241, 0.91509367, 0.94537183, 0.53323223, 0.25249259,
       0.72086206, 0.36743876, 0.49864844, 0.22657505, 0.35356565])

In [404]:
cats = pd.cut(data,4,precision=2)  #precision=2将十进制精度限制在两位
cats

[(0.79, 0.97], (0.6, 0.79], (0.79, 0.97], (0.41, 0.6], (0.22, 0.41], ..., (0.6, 0.79], (0.22, 0.41], (0.41, 0.6], (0.22, 0.41], (0.22, 0.41]]
Length: 20
Categories (4, interval[float64]): [(0.22, 0.41] < (0.41, 0.6] < (0.6, 0.79] < (0.79, 0.97]]

In [405]:
cats.categories

IntervalIndex([(0.22, 0.41], (0.41, 0.6], (0.6, 0.79], (0.79, 0.97]],
              closed='right',
              dtype='interval[float64]')

In [406]:
cats.codes

array([3, 2, 3, 1, 0, 2, 1, 0, 0, 3, 1, 3, 3, 1, 0, 2, 0, 1, 0, 0],
      dtype=int8)

In [407]:
data = np.random.randn(1000)  #1000个正态分布随机数
cats = pd.cut(data,4)   #分为四份

In [408]:
cats

[(0.489, 2.208], (-2.956, -1.23], (0.489, 2.208], (0.489, 2.208], (0.489, 2.208], ..., (-2.956, -1.23], (0.489, 2.208], (0.489, 2.208], (-1.23, 0.489], (-1.23, 0.489]]
Length: 1000
Categories (4, interval[float64]): [(-2.956, -1.23] < (-1.23, 0.489] < (0.489, 2.208] < (2.208, 3.928]]

In [409]:
pd.value_counts(cats)

(-1.23, 0.489]     597
(0.489, 2.208]     299
(-2.956, -1.23]     94
(2.208, 3.928]      10
dtype: int64

In [410]:
#与cut类似，可以传入自定义的分位数（0和1之间的数据，包括边）：
cats = pd.qcut(data,[0,0.1,0.5,0.9,1])

In [411]:
pd.value_counts(cats)

(-0.0265, 1.287]                 400
(-1.187, -0.0265]                400
(1.287, 3.928]                   100
(-2.9499999999999997, -1.187]    100
dtype: int64

### 检测和过滤异常值

In [412]:
data = pd.DataFrame(np.random.randn(1000,4))

In [413]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.045383     0.024079    -0.004794    -0.050389
std       0.997796     1.008737     0.996599     0.996706
min      -3.645860    -3.184377    -3.745356    -3.428254
25%      -0.600254    -0.612162    -0.697084    -0.747478
50%       0.040150    -0.013609    -0.029924    -0.088274
75%       0.746527     0.690847     0.699046     0.623331
max       2.653656     3.525865     2.735527     3.366626

In [414]:
#找出任意一列中绝对值大于三的值：
col=data[2]
col[np.abs(col)>3]

38    -3.399312
133   -3.745356
Name: 2, dtype: float64

In [415]:
#选出所有值大于3或者小于-3的行，对布尔值DataFrame使用any的方法：
data[(np.abs(data)>3).any(1)]

0         1         2         3
38   0.457246 -0.025907 -3.399312 -0.974657
57   1.951312  3.260383  0.963301  1.201206
133  0.508391 -0.196713 -3.745356 -1.520113
232 -0.242459 -3.056990  1.918403 -0.578828
255  0.682841  0.326045  0.425384 -3.428254
319  1.179227 -3.184377  1.369891 -1.074833
541 -3.548824  1.553205 -2.186301  1.277104
632 -0.578093  0.193299  1.397822  3.366626
779 -0.207434  3.525865  0.283070  0.544635
800 -3.645860  0.255475 -0.549574 -1.907459

In [416]:
data[np.abs(data)>3] = np.sign(data) * 3  
#np.sign(data)根据数据中值的正负分别生成-1，1的数值，这里的代码限制了-3到3之间的数值

In [417]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.046577     0.023534    -0.003650    -0.050328
std       0.993777     1.005496     0.992788     0.994152
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.600254    -0.612162    -0.697084    -0.747478
50%       0.040150    -0.013609    -0.029924    -0.088274
75%       0.746527     0.690847     0.699046     0.623331
max       2.653656     3.000000     2.735527     3.000000

In [418]:
np.sign(data).head()

0    1    2    3
0 -1.0 -1.0  1.0 -1.0
1 -1.0  1.0 -1.0 -1.0
2  1.0 -1.0  1.0 -1.0
3  1.0 -1.0  1.0 -1.0
4 -1.0 -1.0 -1.0 -1.0

### 置换和随机抽样

In [419]:
#使用numpy.random.permutation对df中的series或行进行置换（随机重排序）

In [420]:
df = pd.DataFrame(np.arange(5*4).reshape((5,4)))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [421]:
sampler = np.random.permutation(5)

In [422]:
sampler

array([2, 4, 1, 0, 3])

In [423]:
df.take(sampler)

0   1   2   3
2   8   9  10  11
4  16  17  18  19
1   4   5   6   7
0   0   1   2   3
3  12  13  14  15

In [424]:
# 选出一个不含有替代值的随机子集，使用series和df的sample方法：
# sample()函数常用来随机获取dataFrame中数据，可以用于快速查看。
# 常用的有以下入参：
# n ：指定获取的数量，默认为1
# axis：指定随机获取的是行还是列。0表示行，1表示列，默认为0
# weitghts：指定权重信息，需要与 行或者列的数目相等，为列表
# frac：百分比，随机获取的百分比比重

In [425]:
df.sample(n=3,axis=0)

0   1   2   3
2   8   9  10  11
4  16  17  18  19
1   4   5   6   7

In [426]:
#生成一个带有替代值的样本（允许有重复选择），将replace=True传入sample中：

In [427]:
choices = pd.Series([5,7,-1,6,4])
draws = choices.sample(n=10,replace=True)
draws

4    4
1    7
2   -1
3    6
4    4
1    7
4    4
0    5
3    6
0    5
dtype: int64

### 计算指标/虚拟变量

In [428]:
#将分类变量转换为“虚拟”或“指标”矩阵是另外一种用于统计建模或者机器学习的转换操作，如果df中一列有k个不同的值，可以衍生一个k列的值为1和0的矩阵
#或者df。pd.get_dummies()实现该功能

In [429]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'],'data1':range(6)})

In [430]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [431]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [432]:
pd.get_dummies(df['data1'])

0  1  2  3  4  5
0  1  0  0  0  0  0
1  0  1  0  0  0  0
2  0  0  1  0  0  0
3  0  0  0  1  0  0
4  0  0  0  0  1  0
5  0  0  0  0  0  1

In [433]:
#某些情况下，在指标df的列上加入前缀，然后与其他的数据合并。在get_dummies方法中有一个前缀参数用于实现该功能：
dummies = pd.get_dummies(df['key'],prefix='key')
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [434]:
df_with_dummny = df[['data1']].join(dummies)

In [435]:
df_with_dummny

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [436]:
#若df中的一行属于多个类别，则情况会略微复杂

In [437]:
mnames = ['movieid','title','genres']
movies = pd.read_table('/Users/totore/Desktop/pydata-book-2nd-edition/datasets/movielens/movies.dat',sep='::',header=None,names=mnames)
movies[:10]

/Users/totore/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


movieid                               title                        genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy
5        6                         Heat (1995)         Action|Crime|Thriller
6        7                      Sabrina (1995)                Comedy|Romance
7        8                 Tom and Huck (1995)          Adventure|Children's
8        9                 Sudden Death (1995)                        Action
9       10                    GoldenEye (1995)     Action|Adventure|Thriller

In [438]:
#为每个电影流派添加指标变量需要进行一些数据处理。首先从数据集中提取所有不同流派的列表：
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [439]:
genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [440]:
#使用全0的df是构建指标df的一种方式：
zero_matrix = np.zeros((len(movies),len(genres)))

In [441]:
zero_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [442]:
zero_matrix.shape

(3883, 18)

In [443]:
dummies = pd.DataFrame(zero_matrix,columns=genres)
dummies.head()

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  Action  \
0        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   
1        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   
2        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   
3        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   
4        0.0         0.0     0.0        0.0      0.0      0.0    0.0     0.0   

   Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  Mystery  \
0    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
1    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
2    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
3    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
4    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   

   Film-Noir  Western  
0        0.0      0.0  
1        0.0      0.0  
2        0.0      0.0  
3        0.0      0.0  
4        0.0      0.0

In [444]:
#遍历每一部电影，将dummies每一行条目设置为1，使用dummies.columns计算每一个流派的列指标：

In [445]:
gen = movies.genres[0]
gen

"Animation|Children's|Comedy"

In [446]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [447]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [448]:
#使用loc根据这些指标来设置值：

In [449]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i,indices]=1

In [450]:
movies_windic = movies.join(dummies.add_prefix('Genre'))

In [451]:
movies_windic.head()

movieid                               title                        genres  \
0        1                    Toy Story (1995)   Animation|Children's|Comedy   
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy   
2        3             Grumpier Old Men (1995)                Comedy|Romance   
3        4            Waiting to Exhale (1995)                  Comedy|Drama   
4        5  Father of the Bride Part II (1995)                        Comedy   

   GenreAnimation  GenreChildren's  GenreComedy  GenreAdventure  GenreFantasy  \
0             1.0              1.0          1.0             0.0           0.0   
1             0.0              1.0          0.0             1.0           1.0   
2             0.0              0.0          1.0             0.0           0.0   
3             0.0              0.0          1.0             0.0           0.0   
4             0.0              0.0          1.0             0.0           0.0   

   GenreRomance  GenreDrama  ...  GenreCrime  GenreThriller  GenreHorror  \
0           0.0         0.0  ...         0.0            0.0          0.0   
1           0.0         0.0  ...         0.0            0.0          0.0   
2           1.0         0.0  ...         0.0            0.0          0.0   
3           0.0         1.0  ...         0.0            0.0          0.0   
4           0.0         0.0  ...         0.0            0.0          0.0   

   GenreSci-Fi  GenreDocumentary  GenreWar  GenreMusical  GenreMystery  \
0          0.0               0.0       0.0           0.0           0.0   
1          0.0               0.0       0.0           0.0           0.0   
2          0.0               0.0       0.0           0.0           0.0   
3          0.0               0.0       0.0           0.0           0.0   
4          0.0               0.0       0.0           0.0           0.0   

   GenreFilm-Noir  GenreWestern  
0             0.0           0.0  
1             0.0           0.0  
2             0.0           0.0  
3             0.0           0.0  
4             0.0           0.0  

[5 rows x 21 columns]

In [452]:
movies_windic.iloc[0]

movieid                                       1
title                          Toy Story (1995)
genres              Animation|Children's|Comedy
GenreAnimation                                1
GenreChildren's                               1
GenreComedy                                   1
GenreAdventure                                0
GenreFantasy                                  0
GenreRomance                                  0
GenreDrama                                    0
GenreAction                                   0
GenreCrime                                    0
GenreThriller                                 0
GenreHorror                                   0
GenreSci-Fi                                   0
GenreDocumentary                              0
GenreWar                                      0
GenreMusical                                  0
GenreMystery                                  0
GenreFilm-Noir                                0
GenreWestern                            

In [453]:
#对于更大的数据，以上这种使用多成员构建指标变量不快速。更好的是写一个直接将数据写为np数组的底层函数，将结果封装进df

In [454]:
#将get_dummies和cut等离散化函数结合使用是统计应用的一个用用方法：

In [455]:
np.random.seed(12345)
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [456]:
bins = [0,0.2,0.4,0.6,0.8,1]

In [457]:
pd.cut(values,bins)

[(0.8, 1.0], (0.2, 0.4], (0.0, 0.2], (0.2, 0.4], (0.4, 0.6], (0.4, 0.6], (0.8, 1.0], (0.6, 0.8], (0.6, 0.8], (0.6, 0.8]]
Categories (5, interval[float64]): [(0.0, 0.2] < (0.2, 0.4] < (0.4, 0.6] < (0.6, 0.8] < (0.8, 1.0]]

In [458]:
pd.get_dummies(pd.cut(values,bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

### 字符串操作

#### 字符串对象方法

In [459]:
#内建的字符串方法，例如：一个逗号分隔的字符串可以使用split方法拆分成多块

In [460]:
val = 'a,b,  guido'

In [461]:
val.split(',')

['a', 'b', '  guido']

In [462]:
#strip用于清除空格：
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [463]:
first, second, third = pieces

In [464]:
first + '::' + second + '::' + third

'a::b::guido'

In [465]:
#更加pythonic的方法：
'::'.join(pieces)

'a::b::guido'

In [466]:
#定位字符串，使用Python的in关键字是检测子字符串的最佳方法，尽管index和find也能实现同样功能：
'guido' in val

True

In [467]:
val.index(',')

1

In [468]:
val.find('p')

-1

In [469]:
#find和index的区别在于index在字符串中没有找到时返回异常，而find返回-1

In [470]:
#count返回某个特定子字符串在字符串中出现的次数：
val.count(',')

2

In [471]:
#replace将用一种模式替代另一种模式，也通常用于传入空字符来删除某个模式

In [472]:
val.replace(',','::')

'a::b::  guido'

In [473]:
val.replace(',',"")

'ab  guido'

Python 内建字符串：
count
endswith
startswith
jpin
index
find
rfind
replace
strip,rstrip,lstrip
split
lower
upper
casefold
ljust,rjust

#### 字符串正则表达式：提供一种在文本中灵活查找或匹配字符串模式的方法，单个表达式通常称为regex

In [526]:
import re

In [527]:
text = 'foo  bar\t baz  \tqux'

In [528]:
#描述一个或者多个空白字符的正则表达式为\s+
re.split('\s+',text)

['foo', 'bar', 'baz', 'qux']

In [529]:
#当调用re.split('\s+,text')，正则表达式首先会被编译，然后正则表达式的split方法在传入文本上调用。使用re.cpmpile自行编译形成一个
#可复用的正则表达式对象

In [530]:
regex = re.compile('\s+')

In [531]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [480]:
#获得一个所有匹配正则表达式模式列表，使用findall：
regex.findall(text)

['  ', '\t ', '  \t']

In [481]:
#match,search与findall相关性很大。findall返回字符串的所有匹配项，而search返回的仅仅是第一个匹配项。match更为严格，只在字符串的起始位置
#进行匹配。

In [482]:
text = """Dave dave@google.com
Steve steve@gmial.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""

pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
#re.IGNORECASE使正则表达式不区分大小写
regex = re.compile(pattern, flags=re.IGNORECASE)

In [483]:
regex.findall(text)

['dave@google.com', 'steve@gmial.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [484]:
m = regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [485]:
text[m.start():m.end()]

'dave@google.com'

In [486]:
#match只在模式出现于字符串起始位置进行匹配，如没有匹配到，返回None
print(regex.match(text))

None


In [487]:
#sub会返回一个新的字符串，原字符串中的模式会被一个新的字符串替代：
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [488]:
#查找电子邮件地址，将每个地址分为三个部分：用户名、域名和域名后缀。可用括号将模式包起来：

In [523]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'

In [524]:
regex = re.compile(pattern,flags=re.IGNORECASE)

In [491]:
m = regex.match('wesm@bright.net')
m.groups()

('wesm', 'bright', 'net')

In [492]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmial', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [493]:
#sub也可以使用特殊符号，访问每个匹配对象中的分组，符号\1代表第一个匹配分组，\2第二个匹配分组，以此类推

In [494]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3',text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmial, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


正则表达式方法：
findall
finditer
match
search
split
sub,subn

#### Pandas中的向量化字符串函数

In [495]:
data = {'Dave':'dave@google.com','Steve':'steve@gmail.com','Rob':'rob@gmail.com','Wes':np.nan}

In [496]:
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [497]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [498]:
#使用data.map将字符串和有效地正则表达式方法（lambda或其他函数方式传递）应用到每个值上，但在NA值上会失败。

In [499]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [500]:
#正则表达式结合任意的re模块选项使用

In [501]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [502]:
data.str.findall(pattern,flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [503]:
#多种方法进行向量化的元素检索，可以使用str.get或在str属性内部索引：

In [504]:
matches = data.str.match(pattern,flags=re.IGNORECASE)

In [510]:
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [525]:
matches.str

AttributeError: Can only use .str accessor with string values!